
services:
  consumer:
    image: itziarmensaupc/connector:0.0.1
    platform: linux/amd64
    container_name: edc-consumer-68304e4325114036e63d6662
    ports:
      - "29191:29191"
      - "29193:29193"
      - "29194:29194"
      - "29291:29291"
      - "29192:29192"
      - "29195:29195"
    environment:
      - EDC_KEYSTORE_PASSWORD=654321
    volumes:
      - ./resources/configuration:/app/configuration
      - ./resources/certs:/app/certs
