

services:
  postgres:
    image: postgres:15
    container_name: edc_postgres
    environment:
      POSTGRES_DB: edc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - edc-network

volumes:
  postgres_data:

networks:
  edc-network:
    external: true
