
services:
  provider:
    image: itziarmensaupc/connector:0.0.1
    platform: linux/amd64
    container_name: edc-provider-682f0a69b743d545188733d8
    ports:
      - "19191:19191"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"
      - "19192:19192"
      - "19195:19195"
    environment:
      - EDC_KEYSTORE_PASSWORD=123456
    volumes:
      - ./resources/configuration:/app/configuration
      - ./resources/certs:/app/certs

    networks:
      - edc-network

networks:
  edc-network:
    external: true
